categorias/urls.py
from django.urls import path
from .views import CategoriaCriar, CategoriaListar, CategoriaEditar, CategoriaExcluir


app_name = 'categorias'
urlpatterns = [
    path('criar/', CategoriaCriar.as_view(), name='categoria_criar'),
    path('listar/', CategoriaListar.as_view(), name='categoria_listar'),
    path('<int:pk>/editar/', CategoriaEditar.as_view(), name='categoria_editar'),
    path('<int:pk>/excluir/', CategoriaExcluir.as_view(), name='categoria_excluir')
]

core/urls.py
from django.urls import path
from .views import Inicio


app_name = 'core'
urlpatterns = [
    path('', Inicio.as_view(), name='inicio')
]

crono/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('postagens/', include('postagens.urls', namespace='postagens')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categorias/models.py
from django.db import models


class Categoria(models.Model):
    nome = models.CharField(max_length=250)

    def __str__(self):
        return self.nome

categorias/forms.py
from django import forms
from .models import Categoria


class CategoriaForm(forms.ModelForm):
    
    class Meta:
        model = Categoria
        fields = ('nome',)
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'})
        }

categorias/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from usuarios.permissions import AdministradorPermission
from django.views import generic
from .models import Categoria
from .forms import CategoriaForm
from django.urls import reverse_lazy


class CategoriaCriar(LoginRequiredMixin, AdministradorPermission, generic.CreateView):
    form_class = CategoriaForm
    model = Categoria
    success_url = reverse_lazy('categorias:categoria_listar')


class CategoriaListar(LoginRequiredMixin, AdministradorPermission, generic.ListView):
    model = Categoria


class CategoriaEditar(LoginRequiredMixin, AdministradorPermission, generic.UpdateView):
    form_class = CategoriaForm
    model = Categoria
    success_url = reverse_lazy('categorias:categoria_listar')


class CategoriaExcluir(LoginRequiredMixin, AdministradorPermission, generic.DeleteView):
    model = Categoria
    success_url = reverse_lazy('categorias:categoria_listar')

templates/categorias/categoria_confirm_delete.html
<div class="modal fade" id="deleteModal">
    <form action="{% url 'categorias:categoria_excluir' object.pk %}" class="modal-dialog modal-dialog-centered" method="post">
        {% csrf_token %}
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">Excluir categoria</h1>
                <button class="btn-close" data-bs-dismiss="modal" type="button"></button>
            </div>
            <div class="modal-body">
                <p class="mb-0">Tem certeza que deseja excluir essa categoria?</p>
            </div>
            <div class="modal-footer">
                <button class="btn_cinza" data-bs-dismiss="modal" type="button">Cancelar</button>
                <button class="btn_vermelho" type="submit">Excluir</button>
            </div>
        </div>
    </form>
</div>

templates/categorias/categoria_form.html
{% extends 'base.html' %}
{% block main %}
<form method="post">
    {% csrf_token %}
    <div>
        <label class="form-label">Nome</label>
        {{ form.nome }}
    </div>
    <hr>
    <div>
        <button class="btn_azul" type="submit">Enviar</button>
    </div>
</form>
{% endblock main %}

templates/categorias/categoria_list.html
{% extends "base.html" %}
{% block main %}
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.nome }}</td>
            <td>
                <a class="me-3" href="{% url 'categorias:categoria_editar' object.pk %}"><i class="bi bi-pencil-square"></i></a>
                <a data-bs-toggle="modal" href="#deleteModal"><i class="bi bi-x-lg"></i></a>
                {% include 'categorias/categoria_confirm_delete.html' %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td class="text-center" colspan="2">
                <p class="mb-0">Não existem categorias cadastradas</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="d-flex justify-content-start w-100">
    <a href="{% url 'categorias:categoria_criar' %}"><button class="btn_azul">Novo</button></a>
</div>
{% endblock %}