categorias/urls.py
from django.urls import path
from .views import CategoriaCriar, CategoriaListar, CategoriaEditar, CategoriaExcluir


app_name = 'categorias'
urlpatterns = [
    path('criar/', CategoriaCriar.as_view(), name='categoria_criar'),
    path('listar/', CategoriaListar.as_view(), name='categoria_listar'),
    path('<int:pk>/editar/', CategoriaEditar.as_view(), name='categoria_editar'),
    path('<int:pk>/excluir/', CategoriaExcluir.as_view(), name='categoria_excluir')
]

core/urls.py
from django.urls import path
from .views import Inicio


app_name = 'core'
urlpatterns = [
    path('', Inicio.as_view(), name='inicio')
]

crono/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('postagens/', include('postagens.urls', namespace='postagens')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path, include
from .views import UsuarioListar, AdministradorCriar, ProfessorCriar


app_name = 'usuarios'
urlpatterns = [
    path('listar/', UsuarioListar.as_view(), name='usuario_listar'),
    path('administrador/criar', AdministradorCriar.as_view(), name='admiministrador_criar'),
    path('professor/criar', ProfessorCriar.as_view(), name='professor_criar')
]

usuarios/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.db import models
from categorias.models import Categoria


class Usuario(AbstractUser):
    nome = models.CharField(max_length=250)
    first_name = None
    last_name = None


class Administrador(Usuario):

    def save(self, *args, **kwargs):
        super(Administrador, self).save(*args, **kwargs)
        grupo, _ = Group.objects.get_or_create(name='Administradores')
        self.groups.add(grupo)


class Professor(Usuario):
    bio = models.TextField(max_length=500, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, blank=True, null=True)

    def save(self, *args, **kwargs):
        super(Professor, self).save(*args, **kwargs)
        grupo, _ = Group.objects.get_or_create(name='Professores')
        self.groups.add(grupo)

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Administrador, Professor


class AdministradorRegistrationForm(UserCreationForm):

    class Meta:
        model = Administrador
        fields = ('username', 'email', 'nome', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'})
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_superuser = True
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class ProfessorRegistrationForm(UserCreationForm):

    class Meta:
        model = Professor
        fields = ('username', 'email', 'nome', 'bio', 'categoria', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class': 'form-select'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'})
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

usuarios/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from .permissions import AdministradorPermission
from django.views import generic
from .models import Usuario, Administrador, Professor
from .forms import AdministradorRegistrationForm, ProfessorRegistrationForm
from django.urls import reverse_lazy


class UsuarioListar(LoginRequiredMixin, AdministradorPermission, generic.ListView):
    model = Usuario


class AdministradorCriar(LoginRequiredMixin, AdministradorPermission, generic.CreateView):
    form_class = AdministradorRegistrationForm
    model = Administrador
    success_url = reverse_lazy('core:inicio')


class ProfessorCriar(generic.CreateView):
    form_class = ProfessorRegistrationForm
    model = Professor
    success_url = reverse_lazy('core:inicio')

templates/usuarios/administrador_form.html
{% extends 'base.html' %}
{% block main %}
<div>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Nome</label>
            {{ form.nome }}
        </div>
        <div class="mb-3">
            <label class="form-label">Nome de usuário</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="form-label">Senha</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="form-label">Confirme a senha</label>
            {{ form.password2 }}
        </div>
        <hr>
        <div>
            <button class="btn_azul" type="submit">Criar</button>
        </div>
    </form>
</div>
{% endblock main %}

templates/usuarios/professor_form.html
{% extends 'base.html' %}
{% block main %}
<div>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Nome de usuário</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="form-label">Nome</label>
            {{ form.nome }}
        </div>
        <div class="mb-3">
            <label class="form-label">Biografia</label>
            {{ form.bio }}
        </div>
        <div class="mb-3">
            <label class="form-label">Categoria</label>
            {{ form.categoria }}
        </div>
        <div class="mb-3">
            <label class="form-label">Senha</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="form-label">Confirme a senha</label>
            {{ form.password2 }}
        </div>
        <hr>
        <div>
            <button class="btn_azul" type="submit">Criar</button>
        </div>
    </form>
</div>
{% endblock main %}

templates/usuarios/usuario_list.html
{% extends "base.html" %}
{% block main %}
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.nome }}</td>
            <td>
                <a class="me-3" href="{% url 'categorias:categoria_editar' object.pk %}"><i class="bi bi-pencil-square"></i></a>
                <a data-bs-toggle="modal" href="#deleteModal"><i class="bi bi-x-lg"></i></a>
                {% include 'categorias/categoria_confirm_delete.html' %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td class="text-center" colspan="2">
                <p class="mb-0">Não existem categorias cadastradas</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="d-flex justify-content-start w-100">
    <a class="me-2" href="{% url 'usuarios:administrador_criar' %}"><button class="btn_azul">Novo administrador</button></a>
    <a href="{% url 'usuarios:professor_criar' %}"><button class="btn_azul">Novo professor</button></a>
</div>
{% endblock %}