core/urls.py
from django.urls import path
from .views import Inicio


app_name = 'core'
urlpatterns = [
    path('', Inicio.as_view(), name='inicio')
]

crono/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('postagens/', include('postagens.urls', namespace='postagens')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>
        {% block titulo %}
        Crono
        {% endblock titulo %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="p-3">
        <a href="{% if request.path != '/inicio/' %}{% url 'core:inicio' %}{% endif %}">
            <h1 class="fs-3 fw-bold mb-0">Crono</h1>
        </a>
        {% if user.is_authenticated %}
        <a class="text-white fw-medium fs-5" data-bs-toggle="dropdown" href="" role="button">Perfil</a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'logout' %}">Sair</a></li>
        </ul>
        {% endif %}

    </header>
    <main class="p-3">
        {% block main %}
        {% endblock main %}
    </main>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</html>