core/urls.py
from django.urls import path
from .views import Inicio


app_name = 'core'
urlpatterns = [
    path('', Inicio.as_view(), name='inicio')
]

crono/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categorias.urls', namespace='categorias')),
    path('postagens/', include('postagens.urls', namespace='postagens')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postagens/urls.py
from django.urls import path
from .views import PostagemCriar, PostagemListar, PostagemEditar, PostagemExcluir

app_name = 'postagens'
urlpatterns = [
    path('criar/', PostagemCriar.as_view(), name='postagem_criar'),
    path('listar/', PostagemListar.as_view(), name='postagem_listar'),
    path('<int:pk>/editar/', PostagemEditar.as_view(), name='postagem_editar'),
    path('<int:pk>/excluir/', PostagemExcluir.as_view(), name='postagem_excluir')
]

postagens/models.py
from django.db import models
from usuarios.models import Usuario
from categorias.models import Categoria


class Postagem(models.Model):
    titulo = models.CharField(max_length=250)
    desc = models.TextField()
    arquivo = models.FileField(upload_to='arquivos', blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.titulo

postagens/forms.py
from django import forms
from .models import Postagem


class PostagemForm(forms.ModelForm):
    
    class Meta:
        model = Postagem
        fields = ('titulo', 'desc', 'categoria')
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'desc': forms.Textarea(attrs={'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class': 'form-select'})
        }

postagens/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from usuarios.permissions import AdministradorPermission, ProfessorPermission
from django.views import generic
from .models import Postagem
from .forms import PostagemForm
from django.urls import reverse_lazy


class PostagemCriar(LoginRequiredMixin, AdministradorPermission, ProfessorPermission, generic.CreateView):
    form_class = PostagemForm
    model = Postagem
    success_url = reverse_lazy('core:inicio')


class PostagemListar(LoginRequiredMixin, AdministradorPermission, generic.ListView):
    model = Postagem


class PostagemEditar(LoginRequiredMixin, AdministradorPermission, generic.UpdateView):
    form_class = PostagemForm
    model = Postagem
    success_url = reverse_lazy('postagens:postagem_listar')


class PostagemExcluir(LoginRequiredMixin, AdministradorPermission, generic.DeleteView):
    model = Postagem
    success_url = reverse_lazy('postagens:postagem_listar')

templates/postagens/postagem_confirm_delete.html
<div class="modal fade" id="deleteModal">
    <form action="{% url 'postagens:postagem_excluir' object.pk %}" class="modal-dialog modal-dialog-centered" method="post">
        {% csrf_token %}
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5">Excluir postagem</h1>
                <button class="btn-close" data-bs-dismiss="modal" type="button"></button>
            </div>
            <div class="modal-body">
                <p class="mb-0">Tem certeza que deseja excluir essa postagem?</p>
            </div>
            <div class="modal-footer">
                <button class="btn_cinza" data-bs-dismiss="modal" type="button">Cancelar</button>
                <button class="btn_vermelho" type="submit">Excluir</button>
            </div>
        </div>
    </form>
</div>

templates/postagens/postagem_form.html
{% extends 'base.html' %}
{% block main %}
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Título</label>
        {{ form.titulo }}
    </div>
    <div class="mb-3">
        <label class="form-label">Descrição</label>
        {{ form.desc }}
    </div>
    <div>
        <label class="form-label">Categoria</label>
        {{ form.categoria }}
    </div>
    <hr>
    <div>
        <button class="btn_azul" type="submit">Enviar</button>
    </div>
</form>
{% endblock main %}

templates/postagens/postagem_list.html
{% extends "base.html" %}
{% block main %}
<table class="table">
    <thead>
        <tr>
            <th>Título</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.titulo }}</td>
            <td>
                <a class="me-3" href="{% url 'postagens:postagem_editar' object.pk %}"><i class="bi bi-pencil-square"></i></a>
                <a data-bs-toggle="modal" href="#deleteModal"><i class="bi bi-x-lg"></i></a>
                {% include 'postagens/postagem_confirm_delete.html' %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td class="text-center" colspan="2">
                <p class="mb-0">Não existem postagens cadastradas</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="d-flex justify-content-start w-100">
    <a href="{% url 'postagens:postagem_criar' %}"><button class="btn_azul">Novo</button></a>
</div>
{% endblock %}